name: Deploy to NCP with Password

on:
  push:
    branches:
      - dev_RDB

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to NCP
        env:
          NCP_USER: ${{ secrets.NCP_USER }}
          NCP_HOST: ${{ secrets.NCP_RDB_HOST }}
          NCP_PASSWORD: ${{ secrets.NCP_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          sshpass -p "$NCP_PASSWORD" ssh -o StrictHostKeyChecking=no $NCP_USER@$NCP_HOST << EOF
            cd CV_Search
          
            git fetch origin dev_RDB
            git reset --hard origin/dev_RDB

            echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > .env
            echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> .env
            echo "MYSQL_USER=$MYSQL_USER" >> .env
            echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
          
            docker-compose down || true
            docker-compose up -d --build

            chmod +x init.sh
            ./init.sh "$MYSQL_ROOT_PASSWORD"

            docker image prune -f
          EOF