version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: crawler-mongodb  # 컨테이너 이름 변경
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=crawler_db
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d  # 경로 수정!
      - mongodb_data:/data/db  # 주석 해제
    networks:
      - crawler-network

  mongo-express:
    image: mongo-express
    container_name: crawler-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@crawler-mongodb:27017/  # 수정!
    depends_on:
      - mongodb
    networks:
      - crawler-network

networks:
  crawler-network:
    driver: bridge

volumes:
  mongodb_data: