###################### Filebeat Configuration #########################

# ============================== Filebeat inputs ===============================
filebeat.inputs:
  # Application logs in JSON format
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.log
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true
    processors:
      - add_fields:
          target: ''
          fields:
            log_source: app_logs

  # Docker container logs
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.overwrite_keys: true
    json.message_key: log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

# ================================== General ===================================
name: filebeat
tags: ["crawl-service", "json-logs"]

# ================================= Processors =================================
processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  # Drop health check logs to reduce noise
  - drop_event:
      when:
        contains:
          message: "healthcheck"
  # Ensure timestamp is properly formatted
  - timestamp:
      field: "@timestamp"
      layouts:
        - "2006-01-02T15:04:05Z"
        - "2006-01-02T15:04:05.999Z"
      test:
        - "2021-01-01T00:00:00Z"
        - "2021-01-01T00:00:00.000Z"
      ignore_missing: true

# ================================== Outputs ===================================
output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-nginx-%{+yyyy.MM.dd}"
      when.equals:
        container.name: "myweb-proxy"
    - index: "filebeat-api-%{+yyyy.MM.dd}"
      when.equals:
        container.name: "myweb-api"
    - index: "filebeat-crawl-%{+yyyy.MM.dd}"
      when.equals:
        container.name: "myweb-crawl"
    - index: "filebeat-%{+yyyy.MM.dd}"

# ================================= Logging ===================================
logging.level: info
logging.to_files: false
logging.to_stderr: true

# ============================= Path Configuration ============================
path.data: /usr/share/filebeat/data

# =============================== Kibana =====================================
setup.kibana:
  host: "kibana:5601"

# ============================== Dashboards ===============================
setup.dashboards.enabled: true

# ============================= Elasticsearch Template ===========================
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression