name: Docker Compose Deploy to NCP in dev_typescript branch
run-name: Deploying to NCP in dev_typescript branch

on:
  push:
    branches:
      - dev_typescript  # 메인 브랜치에 푸시될 때 실행
    paths:
      - 'crawl-ts/**'  # crawl 디렉토리 내의 파일이 변경된 경우만 실행
      - 'docker-compose.yml'  # docker-compose.yml 파일이 변경된 경우만 실행
  workflow_dispatch:
    inputs:
      action:
        description: '실행할 작업'
        required: true
        default: 'deploy'
        type: choice
        options:
          - 'deploy'
          - 'restart'
          - 'stop'
          - 'update'

jobs:
  build-and-push:
    name: 이미지 빌드 및 푸시
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 백엔드 Docker 이미지 빌드 및 푸시
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/crawl-server:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/crawl-server:latest

      - name: 이미지 상태 확인
        run: |
          echo "백엔드 이미지: ${{ secrets.DOCKER_USERNAME }}/crawl-server:latest"

  deploy:
    name: NCP 서버 배포
    runs-on: ubuntu-latest
    needs : build-and-push
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: 현재 디렉토리 파일 목록 확인
        run: ls -la

      - name: 환경 변수 적용 - docker-compose.yml 업데이트
        run: |
          cat docker-compose.yml

      - name: CV_Search 디렉토리 생성 및 이동
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            # 작업 디렉토리 생성 및 이동
            mkdir -p ~/CV_Search


            # Docker Hub 로그인
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: docker-compose 파일 전송 및 배포
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          source: "./docker-compose.yml"
          target: "~/CV_Search/"


      - name: 배포 실행 및 확인
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            cd ~/CV_Search
            docker-compose pull
            docker-compose up -d --remove-orphans
            docker-compose ps
            docker-compose logs --tail=100